<script src="{{Vite::asset('resources/dist/js/jquery-3.6.0.min.js')}}"></script>
<script src="{{Vite::asset('resources/dist/js/popper.min.js')}} "></script>
<script src="{{Vite::asset('resources/dist/js/tooltip.js')}} "></script>
<script src="{{Vite::asset('resources/dist/js/bootstrap.min.js')}} "></script>
<script src="{{Vite::asset('resources/dist/js/jquery.nicescroll.min.js')}} "></script>
<script src="{{Vite::asset('resources/dist/js/moment.min.js')}} "></script>
<script src="{{Vite::asset('resources/dist/js/stisla.js')}} "></script>
<script src="{{Vite::asset('resources/dist/js/jscolor.js')}} "></script>
<script src="{{Vite::asset('resources/dist/js/bootstrap-datepicker.min.js')}} "></script>
<script src="{{Vite::asset('resources/dist/js/bootstrap-timepicker.min.js')}} "></script>
<script src="{{Vite::asset('resources/dist/js/bootstrap-tagsinput.min.js')}} "></script>
<script src="{{Vite::asset('resources/dist/js/select2.full.min.js')}} "></script>
<script src="{{Vite::asset('resources/dist/js/summernote-bs4.js')}} "></script>
<script src="{{Vite::asset('resources/dist/js/jquery.dataTables.min.js')}} "></script>
<script src="{{Vite::asset('resources/dist/js/dataTables.bootstrap4.min.js')}} "></script>
<script src="{{Vite::asset('resources/dist/js/iziToast.min.js')}} "></script>
<script src="{{Vite::asset('resources/dist/js/fontawesome-iconpicker.js')}} "></script>
<script src="{{Vite::asset('resources/dist/js/bootstrap4-toggle.min.js')}} "></script>